---
- name: Apply Docker containerization tasks
  ansible.builtin.include_tasks: docker/main.yml

- name: Ensure Docker is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add the deployer user to the docker group
  ansible.builtin.user:
    name: "{{ civa_deployer_user }}"
    groups: docker
    append: true
