---
- name: civa multi-server bootstrap
  hosts: civa_targets
  become: true
  gather_facts: true
  collections:
    - civa.bootstrap
    - civa.system_update
    - civa.user_management
    - civa.ssh_hardening
    - civa.security_firewall
    - civa.system_config
    - civa.dependencies
    - civa.containerization
    - civa.webserver

  roles:
    - role: bootstrap
      tags:
        - always
    - role: system_update
      tags:
        - system_update
    - role: user_management
      tags:
        - user_management
    - role: ssh_hardening
      tags:
        - ssh_hardening
    - role: security_firewall
      tags:
        - security_firewall
    - role: system_config
      tags:
        - system_config
    - role: dependencies
      tags:
        - dependencies
    - role: containerization
      tags:
        - containerization
    - role: traefik
      tags:
        - traefik
    - role: nginx
      tags:
        - nginx
    - role: caddy
      tags:
        - caddy
