---
- name: Apply Debian-family firewall tasks
  when: civa_is_debian
  ansible.builtin.include_tasks: vendors/debian.yml

- name: Apply RedHat-family firewall tasks
  when: civa_is_rhel
  ansible.builtin.include_tasks: vendors/redhat.yml

- name: Apply shared firewall and fail2ban setup
  ansible.builtin.include_tasks: common.yml
